2025-06-05 22:48:35.654 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-05 22:48:35.654 | INFO     | __main__:main:38 - Starting database setup...
2025-06-05 22:48:35.655 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-05 22:48:35.656 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\01_drop_tables.sql
2025-06-05 22:48:35.662 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\02_create_tables.sql
2025-06-05 22:48:35.668 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\03_insert_records.sql
2025-06-05 22:48:35.668 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-05 22:48:35.669 | INFO     | __main__:main:65 - Database connection closed.
2025-06-05 22:49:10.510 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-05 22:49:10.511 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:49:10.512 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-05 22:49:10.528 | INFO     | __main__:execute_sql_file:27 - Executed: C:\Repos\datafun-05-sql\sql_features\01_new_column_pub_age.sql
2025-06-05 22:49:10.529 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-05 22:49:10.529 | INFO     | __main__:main:63 - Database connection closed.
2025-06-08 22:49:03.122 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 22:49:03.123 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-08 22:49:03.125 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 22:49:03.129 | ERROR    | __main__:execute_sql_file:29 - Failed to execute C:\Repos\datafun-05-sql\sql_features\01_new_column_pub_age.sql: duplicate column name: author_age_at_publication
2025-06-08 22:49:03.130 | ERROR    | __main__:main:60 - Error during feature queries execution: duplicate column name: author_age_at_publication
2025-06-08 22:49:03.130 | INFO     | __main__:main:63 - Database connection closed.
2025-06-08 22:52:16.174 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 22:52:16.174 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-08 22:52:16.175 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 22:52:16.194 | INFO     | __main__:execute_sql_file:27 - Executed: C:\Repos\datafun-05-sql\sql_features\delete_records.sql
2025-06-08 22:52:16.200 | ERROR    | __main__:execute_sql_file:29 - Failed to execute C:\Repos\datafun-05-sql\sql_features\update_records.sql: no such table: author
2025-06-08 22:52:16.200 | ERROR    | __main__:main:60 - Error during feature queries execution: no such table: author
2025-06-08 22:52:16.201 | INFO     | __main__:main:63 - Database connection closed.
2025-06-08 22:52:42.231 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 22:52:42.231 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-08 22:52:42.233 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 22:52:42.236 | INFO     | __main__:execute_sql_file:27 - Executed: C:\Repos\datafun-05-sql\sql_features\delete_records.sql
2025-06-08 22:52:42.249 | ERROR    | __main__:execute_sql_file:29 - Failed to execute C:\Repos\datafun-05-sql\sql_features\update_records.sql: duplicate column name: author_number_of_books
2025-06-08 22:52:42.250 | ERROR    | __main__:main:60 - Error during feature queries execution: duplicate column name: author_number_of_books
2025-06-08 22:52:42.250 | INFO     | __main__:main:63 - Database connection closed.
2025-06-08 23:00:20.257 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 23:00:20.257 | INFO     | __main__:main:38 - Starting database setup...
2025-06-08 23:00:20.258 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 23:00:20.288 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\01_drop_tables.sql
2025-06-08 23:00:20.294 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\02_create_tables.sql
2025-06-08 23:00:20.297 | ERROR    | __main__:execute_sql_file:32 - Failed to execute C:\Repos\datafun-05-sql\sql_create\03_insert_records.sql: incomplete input
2025-06-08 23:00:20.298 | ERROR    | __main__:main:62 - Error during database setup: incomplete input
2025-06-08 23:00:20.298 | INFO     | __main__:main:65 - Database connection closed.
2025-06-08 23:01:10.108 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 23:01:10.109 | INFO     | __main__:main:38 - Starting database setup...
2025-06-08 23:01:10.111 | INFO     | __main__:main:52 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 23:01:10.127 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\01_drop_tables.sql
2025-06-08 23:01:10.137 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\02_create_tables.sql
2025-06-08 23:01:10.164 | INFO     | __main__:execute_sql_file:30 - Executed: C:\Repos\datafun-05-sql\sql_create\03_insert_records.sql
2025-06-08 23:01:10.165 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-08 23:01:10.165 | INFO     | __main__:main:65 - Database connection closed.
2025-06-08 23:01:48.924 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 23:01:48.924 | INFO     | __main__:main:52 - Starting query execution...
2025-06-08 23:01:48.926 | INFO     | __main__:main:68 - Connected to database: C:\Repos\datafun-05-sql\data\project.sqlite3
2025-06-08 23:01:48.927 | ERROR    | __main__:execute_and_save_query:27 - Failed to execute/save C:\Repos\datafun-05-sql\sql_queries\query_aggreggation.sql: Execution failed on sql 'SELECT a.name AS author_name, COUNT(b.book_id) AS book_count
FROM authors a
LEFT JOIN books b ON a.author_id = b.author_id
GROUP BY a.name;': no such table: authors
2025-06-08 23:01:48.927 | ERROR    | __main__:main:75 - Error during execution: Execution failed on sql 'SELECT a.name AS author_name, COUNT(b.book_id) AS book_count
FROM authors a
LEFT JOIN books b ON a.author_id = b.author_id
GROUP BY a.name;': no such table: authors
2025-06-08 23:01:48.927 | INFO     | __main__:main:78 - Database connection closed.
2025-06-08 23:04:08.322 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 23:04:08.323 | INFO     | __main__:main:52 - Starting query execution...
2025-06-08 23:04:08.324 | INFO     | __main__:main:68 - Connected to database: C:\Repos\datafun-05-sql\data\project.sqlite3
2025-06-08 23:04:08.325 | ERROR    | __main__:execute_and_save_query:27 - Failed to execute/save C:\Repos\datafun-05-sql\sql_queries\query_aggreggation.sql: Execution failed on sql 'SELECT a.name AS author_name, COUNT(b.book_id) AS book_count
FROM authors a
LEFT JOIN books b ON a.author_id = b.author_id
GROUP BY a.name;': no such table: authors
2025-06-08 23:04:08.326 | ERROR    | __main__:main:75 - Error during execution: Execution failed on sql 'SELECT a.name AS author_name, COUNT(b.book_id) AS book_count
FROM authors a
LEFT JOIN books b ON a.author_id = b.author_id
GROUP BY a.name;': no such table: authors
2025-06-08 23:04:08.326 | INFO     | __main__:main:78 - Database connection closed.
2025-06-08 23:05:46.378 | INFO     | utils_logger:<module>:41 - Logging to file: logs\project_log.log
2025-06-08 23:05:46.379 | INFO     | __main__:main:52 - Starting query execution...
2025-06-08 23:05:46.380 | INFO     | __main__:main:68 - Connected to database: C:\Repos\datafun-05-sql\data\db.sqlite
2025-06-08 23:05:46.400 | INFO     | __main__:execute_and_save_query:24 - Executed and saved: C:\Repos\datafun-05-sql\sql_queries\query_aggreggation.sql → C:\Repos\datafun-05-sql\sql_output\query_aggreggation.csv
2025-06-08 23:05:46.403 | INFO     | __main__:execute_and_save_query:24 - Executed and saved: C:\Repos\datafun-05-sql\sql_queries\query_filter.sql → C:\Repos\datafun-05-sql\sql_output\query_filter.csv
2025-06-08 23:05:46.406 | INFO     | __main__:execute_and_save_query:24 - Executed and saved: C:\Repos\datafun-05-sql\sql_queries\query_group_by.sql → C:\Repos\datafun-05-sql\sql_output\query_group_by.csv
2025-06-08 23:05:46.408 | INFO     | __main__:execute_and_save_query:24 - Executed and saved: C:\Repos\datafun-05-sql\sql_queries\query_join.sql → C:\Repos\datafun-05-sql\sql_output\query_join.csv
2025-06-08 23:05:46.412 | INFO     | __main__:execute_and_save_query:24 - Executed and saved: C:\Repos\datafun-05-sql\sql_queries\query_sorting.sql → C:\Repos\datafun-05-sql\sql_output\query_sorting.csv
2025-06-08 23:05:46.412 | INFO     | __main__:main:73 - Query execution and saving completed successfully.
2025-06-08 23:05:46.413 | INFO     | __main__:main:78 - Database connection closed.
